#!/bin/bash --restricted
#

# Tunnelist restricted shell for customers
#
export TIMEFORMAT=$'\nTime this session: %3R seconds.\n'
echo ""
echo "Welcome $USER!"
echo ""
echo "[ Press any key to exit ]"
echo ""
time read 
exit 1
